# 参考：https://github.com/flysnow-org/maupassant-hugo/blob/master/exampleSite/config.toml
baseURL = "https://hanshilei.github.io/"
languageCode = "zh-CN"
title = "Shilei Hugo Site"
theme = "maupassant"

hasCJKLanguage = true
summaryLength = 140

[author]
  name = "Shilei"

[params]
  author = "Shilei"
  subtitle = "专注于K8s、Go语言、移动互联网、软件架构"
  keywords = "k8s,golang,go语言,go语言笔记"
  description = "专注于IT互联网，包括但不限于Go语言(golang)、Python、k8s、项目管理、软件架构等"
  localSearch = true # 启用本地搜索

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = false  # 是否开启目录

## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"
## 配置网站菜单
[menu]
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 2